---
output:
  bookdown::pdf_document2:
    fig_caption: true
    includes: null
    toc: no
---
# Appendix C. Rebuilding analysis for St. Matthew blue king crab {-}

# Introduction{-}
In 2018 the MMB for SMBKC fell below 50% of the $B_{MSY}$ proxy or the MSST, using average mature male biomass from 1978-2017. The stock was determined to be overfished (but overfishing is not occurring since the fishery has been closes the last three years) and a rebuilding plan is to be implemented within 2 years. This document summarizes the projections performed on the 2019 assessment model and their associated rebuilding probabilities for the stock using the projections module developed for GMACS (A.Punt pers Comm). 
All projections presented here are performed on the base or reference model with 2019 data, results include projections that look at a alternative regime for the time frame for reference points calculation.


# Regime shifts{-}
Current model output (using the reference model) of both biomass and recruitment suggest a shift from higher levels in the first have of the time series to lower levels in the recent regime. These trends warrented an examination of analysises to determine if regimes occur in the data.

## Recruitment breakpoint analysis {-}
On examination, it was clear that recruitment for SMBKC has been consistently lower in recent years. Thus, the crab Plan Team requested that the authors conduct a recruitment breakpoint analysis similar to that conducted for Bristol Bay red king crab in 2017 (Zheng et al. 2017) and eastern Bering Sea Tanner crab in 2013 (Stockhausen 2013). The goal of this analysis was to objectively identify a change in stock productivity based on the recruitment time series. This could then be used to develop alternative rebuilding scenarios and also provide alternative BMSY proxies. Results from assessment model 3 from 2018, which is the base or reference model, (Ianelli and Zheng 2018) were used for this analysis. Details of this analysis are presented in Appendix D.

Both Ricker and Beverton-Holt (B-H) models resulted in the same breakpoint brood year of 1989, which corresponded to recruitment year of 1996. The model without a breakpoint (i.e., a single period) was about 26 times less probable than the 1989 breakpoint model for the Ricker stock-recruitment relationship and 4 times less probable than the Beverton-Holt, which suggested a possible change in stock productivity from the early high period to the recent low period. More details of these results can be found in Appendix D.


## STARS method {-}

The “Sequential t-Test Analysis of Regime Shifts (STARS)” method was suggested as a alternative analysis that could be used to determine of the St.Matthew blue king crab stock has undergone a regime shift (Rodionov and Overland 2005). The advantage of this method is that it can be performed on any time series and does not rely on a stock recuitment relationship. . 
This method identifies discontinuity in a time-series and allows for early detection of a regime shift and subsequent monitoring of changes in its magnitude over time (Rodionov 2004).
Detection of discontinuity is accomplished by sequentially testing whether a new mean recruitment value within a time-series represents a statistically significant deviation from the mean value of the current ‘regime.’ As data are added to the time-series, the hypothesis of a new ‘regime’ (i.e. time block) is either confirmed or rejected based on the Student’s t-test (Rodionov and Overland 2005). 
The STARS method is well documented in the literature and has been applied previously to physical and biological indices (Mueter et al. 2007; Reid et al. 2016; Marty 2008; Conversi et al. 2010; Menberg et al. 2014; Blamey et al. 2012; Lindegren et al. 2010; Howard et al. 2007). An R script (STARS.R; Seddon et al. 2011; http://esapubs.org/archive/ecol/E095/262/suppl-1.php) that is equivalent to the v3-2 excel add-in tool (http://www. beringclimate.noaa.gov/regimes), and references the methods from Rodionov 2004 and 2006, was used to run the STARS method on the recruitment time series from the accepted 2018 model output.

Several parameters within the STARS method need specification prior to application to determine the breaks in the recruitment time series.
Two parameters, the p-value (the probability level for significance between ‘regime’ means) and the cutoff length (the approximate minimum number of years within a regime) control the magnitude and scale of the regimes to be detected, or how strong a change in the recruitment needs to be detected.
If regimes are longer than the cutoff length, they will be detected. 
There is a reduced probability of detection for regimes shorter than the cutoff length, but the regimes may still be detected if the shift is of sufficient magnitude (Rodionov 2004).
In addition, Huber’s weight parameter determines the weight assigned to outliers and thus the magnitude of the average values of each regime (Huber 1964). 
Finally, the user determines whether to account for autocorrelation and specifies the associated subsample size needed. 
For this study, a p-value of 0.05 was chosen, which is well within the range of other studies that have applied the STARS method. 
A range of cutoff values from 5 to 20 were specified within the STARS method to explore the sensitivity, but all values produced the same significant break year of 1996. 
The default value of one for Huber’s weight parameter, and autocorrelation were included (Newman et al. 2003). 
Two frameworks are available within the STARS method to estimate autocorrelation (Rodionov 2004): the MPK (Marriott-Pope and Kendall) and the IPN4 (Inverse Proportionality with 4 corrections). The two frameworks break the time series into subsamples, estimate bias-corrected first-order autocorrelation for each subsample and then use the median value of all estimates.
The two frameworks produce very similar results and only in certain instances (small subsample size) does the IPN4 method significantly outperform the MPK method (Rodionov 2004). 
Therefore, the IPN4 method was used in this analysis with the suggested subsample size of m=(l+1)/3, where l is the cutoff length.

This parameterization resulted in two potential time blocks: 1978-1995 and 1996–2017, corresponding to a break in 1996 which is the same year as the recruitment breakpoint analysis that was performed in May 2019.

# Rebuilding projections{-}
The rebuilding projections were performed using the projection module coded into GMACS in early 2019 (A. Punt per Comm). 
A preliminary analysis of the rebuilding projections performed at the January crab plan team meeting by A.Punt concluded that bycatch mortality in this fishery was minor and that the rebuilding timeline was entirely dependent on assumptions of recruitment for the stock. 

Initial rebuilding projections presented at the May CPT meeting (June SSC meeting) included recruitment options of: Ricker, or Beverton-Holt stock recruit relationship and "random" recruitment. Stock-recruitment models (Ricker, Beverton-Holt) typically fit poorly for crab stocks, and this holds true for SMBKC. Projections using these stock recruitment relationships were still provided for initial review since they scale recruitment to the current status of the stock. The "random"" recruitment option resamples historical recruitment estimates randomly, from a designated period for each projection iteration, such as the entire time series 1978 to 2018 as one example. This option assumes that recruitment is unrelated to stock size, but also relies on choosing the random draws from a biologically and environmentally representative time frame of past recruitment. 

Projections were performed to look at a range of combinations of recruitment, bycatch mortality, and implementation of the state harvest policy to determine the probability of recovery for each scenario. 
Rebuilding time under any of the projection combinations is insensitive to the average values for recent (2014 - 2018) bycatch. As a sensitivity analysis the projections presented here were also performed using the maximum observed bycatch value, corresponding to year 2007, and are presented in this document.
The implementation of the state harvest policy in the projections (version "d") affected rebuilding times in some projections, but with a much smaller affect of increasing $T_{min}$ than projections at F = M (0.18), therefore the projections presented here use the state of Alaska harvest policy as the upper bound for fising mortality. 

The projections considered in May produced a range of $T_{min}$ values, however, the decision tackled at this meeting was which option is the most biologically and environmentally plausible. The recruitment breakpoint analysis and analysis using the STARS method suggested that recent recruitment (1996-2017) differed from the early part of the time series. 
Recruitment success for SMBKC, as with many crab species, is strongly driven by environmental conditions. 
In the Bering Sea recent environmental conditions may be unfavorable for recruitment success for this stock, which may be due to the longer larval duration of blue king crab.

Both the CPT and SSC recommendations from the May meeting were to proceed with "random" recruitment projections that drew from two recruitment time periods:   
1) the entire time series, 1978 to 2018
2) the current regime, 1996-2018.
These projections use the state harvest policy as the upper fishing mortality and included average recent bycatch mortality. Additionally, sensitivity on $T_{min}$ values to higher bycatch mortality are included to help inform the rebuilding time frame. 

The important decision points that are needed to move forward with the rebuilding plan are to adapt a consensus on:
the current state of the stock (reference point time frame) and the cooresponding expectations on future recruitment, and the expectations for future bycatch mortality. 


\begin{table}[ht]
\centering
\caption{Projections performed with associated recruitment assumptions.} 
\label{tab:projections}
\begin{tabular}{lcccc}
  \hline
  Projection & recruitment & $B_\mathit{MSY}$ proxy & recruitment years \\ 
  \hline
  1 & random recruitment & 1978-2017 & 1978-2017 \\ 
  5 & random recruitment & 1996-2017 & 1996-2017 \\ 
  \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Versions for each of the projections.} 
\label{tab:versions}
\begin{tabular}{lcccccccc}
  \hline
  Version & Bycatch mortality & SOA harvest policy \\ 
  \hline
  d &  present (2013-2017) & yes \\
  aa & present (max) & yes \\
  \hline
\end{tabular}
\end{table}

# Results {-}

## Bycatch mortality {-}
Rebuilding time under any of the projection combinations is insensitive to the average values for recent (2014 - 2018) bycatch. As a sensitivity analysis the projections presented here were also performed using the maximum observed bycatch value, corresponding to year 2007 in the model.

Update on increases in bycatch mortality - comparison in figures or tables?

## State harvest policy {-}
The implementation of the state harvest policy in the projections (version "d") affected rebuilding times in some projections. 
In most cases the $T_{min}$ estimates increased. The implementation of the state harvest policy is less pessimistic than the maximum F = .0.18, hence we used version "d" for projection evaluations. 

## Stock recruit relationship {-}
Projections (projections 2 and 3) that used a stock recruit relationship assumed that the future recruitment was related to the current and future mature male biomass even though the fit to the stock recruit relationship was weak (Figure 7). These projections produced an intermediate estimate of $T_{min}$ compared to projections 1 and 4, under a Ricker S-R relationship the $T_{min}$= 16.5 years (F = 0) and under a Beverton-Holt S-R relationship the $T_{min}$= 14.5 years (F = 0) (Figure 8). When the state harvest policy is implemented these increase to 28.5 years and 23.5 years, respectively. 

## Mean recruitment {-}
Projections using "random" recruitment (projection 1) resampled from the entire time series (1978-2017) implied environmental conditions as being equal to this period. Under this hypothesis the probability of recovery produces a $T_{min}$ = 7.5 years under no directed fishery mortality (F = 0), and a $T_{min}$ = 11.5 years when the state harvest policy is implemented (Figure 9). The recruitment breakpoint analysis performed on this stock (Appendix A) suggested that recruitment conditions equal to the full period are unlikely and overly optimistic. 

Projections that use "random" recruitment (projection 4) for the recent period (1996-2017) specified by the recruitment breakpoint analysis (Appendix A) were more pessimistic. These suggested that the probability of recovery is low, even extending the projections out to 100 years, under recent recruitment conditions (Figure 10). The period for "random" recruitment was adjusted in this projection and the $B_{MSY}$ proxy was calculated using the entire time series (1978-2017), meaning that recent recruitment was inconsistent with the $B_{MSY}$ proxy that used the full time series. This projection was deemed as unrealistic, since under the current regime, $B_{MSY}$ would need to be consistent with the recent recruitment.


## Updated $B_{MSY}$ proxy and mean recruitment{-}
The recruitment breakpoint analysis suggested that a shift occurred in 1996. Both the "random" recruitment time period and the time period to calculate the $B_{MSY}$ proxy should reflect this (Table \ref{tab:B_msy proxy}). Projection 5 matches these two time frames, and shows that the $T_{min}$ for the probability of recovery to this new/current $B_{MSY}$ proxy is slightly more than 10 years, even under the state harvest policy implementation (Figure 11). This is due to the state harvest policy thresholds being based on past periods rather than having adopted to changes in $B_{MSY}$ proxy years.


# Discussion {-}
The projections considered here produced a range of $T_{min}$ values (Table \ref{tab:t_min}), however, the question remains which option is the most biologically and environmentally plausible. The recruitment breakpoint analysis (Appendix A) suggested that recent recruitment (1996-2017) differed from the early part of the time series. Recruitment success for SMBKC, as with many crab species, is driven by environmental conditions. In the Bering Sea recent environmental conditions appear to be unfavorable for recruitment success for this stock, which may be due to the longer larval duration of blue king crab (reference). 

The most biologically and environmental plausible projection would be projection 4, which suggests that it would be unlikely for the stock to rebuild to the current $B_{MSY}$ proxy under current recruitment conditions. However, adjusting the $B_{MSY}$ time frame (projection 5) would allow the stock to rebuild to a a more representative $B_{MSY}$ that is based on current recruitment conditions. 

Combinations of the projections, weighted based on their plausibility, are possible but more justification and thought is needed to determine why these combinations would be a better representation of the current biology and environment of the stock. Also, reasoning for the weighting of projections in a combination would need to be established. 


## Tables {-}


\begin{table}[ht]
\centering
\caption{$B_{MSY}$ proxy options for 2018 model 3, all Tier 4b.} 
\label{tab:B_msy proxy}
\begin{tabular}{lcccccccc}
  \hline
  Year & Basis for $B_\mathit{MSY}$ & $B_\mathit{MSY}$ proxy & MSST & Biomass($MMB_{mating}$) & B/$B_{MSY}$ & $F_{OFL}$ & M \\ 
  \hline
  2018/19 & 1978-2017 & 3.48 & 1.74 & 1.09 & 0.31 & 0.041 & 0.18 \\ 
  2018/19 & 1978-2017 & 2.03 & 1.015 & 1.08 & 0.53 & 0.087 & 0.18 \\ 
  \hline
\end{tabular}
\end{table}


\begin{table}[ht]
\centering
\caption{$T_{min}$ for each projection version d with no directed fishing (F=0).} 
\label{tab:t_min}
\begin{tabular}{lcccccccc}
  \hline
  Projection & recruitment & $B_\mathit{MSY}$ proxy & recruitment yrs & $T_{min}$ \\ 
  \hline
  1 & random recruitment & 1978-2017 & 1978-2017 & 7.5 years \\ 
  2 & ricker & 1979-2017 &  & 16.5 years \\
  3 & Beverton-Holt & 1979-2017 &  & 14.5 years \\
  4 & random recruitment & 1978-2017 & 1996-2017 & 100+ years \\
  5 & random recruitment & 1996-2017 & 1996-2017 & 10.5 years \\
  6 & random recruitment & 1978-2017 & 1999-2017 & 100+ years \\
  7 & random recruitment & 1978-2017 & 1989-2017 & 10 years \\
  \hline
\end{tabular}
\end{table}


# Figures {-}