---
output:
  pdf_document: default
  html_document: default
---
# Appendix C. Rebuilding analysis for St. Matthew blue king crab 

# Introduction
In 2018 the MMB for SMBKC fell below 50% of the $B_{MSY}$ proxy or the MSST, using average mature male biomass from 1978-2017. The stock was determined to be overfished (but overfishing is not occurring since the fishery has been closes the last two years) and a rebuilding plan is to be implemented. This document summarizes the current stock status, based on the 2018 assessment model, and projections done on rebuilding probabilities for the stock using the projections module developed for GMACS (A.Punt pers Comm). 

## Assessment model - current status
The 2018 assessment model was model 3 (2018 SAFE document, Zheng and Ianelli 2018), which used the 2017 model with updated data from both the NMFS trawl survey and the ADF&G pot survey. Some graphical output of this model is presented here with updates to the GMACS base code made since fall of 2018 (Figures 1-5). The model output is comparable to that presented in Sept. 2018. This model was used in the rebuilding projections. Variants of this model that will be presented in September include models 4 (VAST model prelim) and 5 (Fit survey) presented in 2018. Changes to the GMACS code have shown to have minor impacts on results, so work presented here focuses on rebuilding alternatives for consideration at the May 2019 meeting.


# Rebuilding projections
The rebuilding projections were performed using the projection module coded into GMACS in early 2019 (A. Punt per Comm). 
A preliminary analysis of the rebuilding projections performed at the January crab plan team meeting by A.Punt concluded that bycatch mortality in this fishery was minor and that the rebuilding timeline was entirely dependent on assumptions of recruitment for the stock (Figure 6). 

Recruitment possibilities for the projection model include: Ricker, or Beverton-Holt stock recruit relationship and "random" recruitment. Stock-recruitment models (Ricker, Beverton-Holt) typically fit poorly for crab stocks, and this holds true for SMBKC (Figure 7). Projections using these stock recruitment relationships are still provided here for review since they scale recruitment to the current status of the stock. The "random"" recruitment option resamples historical recruitment estimates randomly, from a designated period for each projection iteration, such as the entire time series 1978 to 2017 as one example. This option assumes that recruitment is unrelated to stock size, but also relies on choosing the random draws from a biologically and environmentally representative time frame of past recruitment. 

Projections were performed to look at a range of combinations of recruitment, bycatch mortality, and implementation of the state harvest policy to determine the probability of recovery for each scenario. The SSC recommendations included a weighted combination of the projections based on their plausibility which is based on the life history and biology of the species. One such weighted combination is explored here but the biological plausibility of each projection assumption requires further feedback and discussion.

\begin{table}[ht]
\centering
\caption{Projections performed with associated recruitment assumptions.} 
\label{tab:projections}
\begin{tabular}{lcccccccc}
  \hline
  Projection & recruitment & $B_\mathit{MSY}$ proxy & recruitment years \\ 
  \hline
  1 & random recruitment & 1978-2017 & 1978-2017 \\ 
  2 & Ricker & 1978-2017 &  \\ 
  3 & Beverton-Holt & 1978-2017 &  \\ 
  4 & random recruitment & 1978-2017 & 1996-2017 \\ 
  5 & random recruitment & 1996-2017 & 1996-2017 \\ 
  6 & random recruitment & 1978-2017 & 1999-2017 \\ 
  7 & random recruitment & 1978-2017 & 1989-2017 \\ 
  \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Versions for each of the projections in Table \ref{tab:projections}.} 
\label{tab:versions}
\begin{tabular}{lcccccccc}
  \hline
  Version & Bycatch mortality & SOA harvest policy \\ 
  \hline
  a &  0 & no \\ 
  b &  present (2013-2017) & no \\  
  c &  0 & yes \\ 
  d &  present (2013-2017) & yes \\ 
  \hline
\end{tabular}
\end{table}


## Results

#### Bycatch mortality 
Average values for recent (2013 - 2017) bycatch is insensitive to rebuilding time under any of the projections. Projections 1a and 1b, which use mean recruitment for the entire time series, clearly showed the lack of influence bycatch mortality had on recovery probability (Figure 6). Therefore, projections under version "a" were omitted from this presentation. 

#### State harvest policy
The implementation of the state harvest policy in the projections (version "d") affected rebuilding times in some projections. 
In most cases the $T_{min}$ estimates increased. The implementation of the state harvest policy is less pessimistic than the maximum F = .0.18, hence we used version "d" for projection evaluations. 

#### Stock recruit relationship 
Projections (projections 2 and 3) that used a stock recruit relationship assumed that the future recruitment was related to the current and future mature male biomass even though the fit to the stock recruit relationship was weak (Figure 7). These projections produced an intermediate estimate of $T_{min}$ compared to projections 1 and 4, under a Ricker S-R relationship the $T_{min}$= 16.5 years (F = 0) and under a Beverton-Holt S-R relationship the $T_{min}$= 14.5 years (F = 0) (Figure 8). When the state harvest policy is implemented these increase to 28.5 years and 23.5 years, respectively. 

#### Mean recruitment 
Projections using "random" recruitment (projection 1) resampled from the entire time series (1978-2017) implied environmental conditions as being equal to this period. Under this hypothesis the probability of recovery produces a $T_{min}$ = 7.5 years under no directed fishery mortality (F = 0), and a $T_{min}$ = 11.5 years when the state harvest policy is implemented (Figure 9). The recruitment breakpoint analysis performed on this stock (Appendix A) suggested that recruitment conditions equal to the full period are unlikely and overly optimistic. 

Projections that use "random" recruitment (projection 4) for the recent period (1996-2017) specified by the recruitment breakpoint analysis (Appendix A) were more pessimistic. These suggested that the probability of recovery is low, even extending the projections out to 100 years, under recent recruitment conditions (Figure 10). The period for "random" recruitment was adjusted in this projection and the $B_{MSY}$ proxy was calculated using the entire time series (1978-2017), meaning that recent recruitment was inconsistent with the $B_{MSY}$ proxy that used the full time series. This projection was deemed as unrealistic, since under the current regime, $B_{MSY}$ would need to be consistent with the recent recruitment.


#### Updated $B_{MSY}$ proxy and mean recruitment
The recruitment breakpoint analysis suggested that a shift occurred in 1996. Both the "random" recruitment time period and the time period to calculate the $B_{MSY}$ proxy should reflect this (Table \ref{tab:B_msy proxy}). Projection 5 matches these two time frames, and shows that the $T_{min}$ for the probability of recovery to this new/current $B_{MSY}$ proxy is slightly more than 10 years, even under the state harvest policy implementation (Figure 11). This is due to the state harvest policy thresholds being based on past periods rather than having adopted to changes in $B_{MSY}$ proxy years.


#### Weighted combinations
When the initial projections were presented at the SSC meeting it was suggested that the Plan Team consider a combination of the projection hypotheses (which would be weighted according to their plausibility). One example of this would be a weighted combination of projection 2d and 4d, with a Ricker S-R relationship and current recruitment time series (1996-2017). This combination, under equal weighting, produces a scaled down version of the projection 2d outcome, with a resulting $T_{min}$ = 24 years (Figure 12). Other possible weighting combinations could be performed after further Plan Team and SSC consultation. 

## Discussion
The projections considered here produced a range of $T_{min}$ values (Table \ref{tab:t_min}), however, the question remains which option is the most biologically and environmentally plausible. The recruitment breakpoint analysis (Appendix A) suggested that recent recruitment (1996-2017) differed from the early part of the time series. Recruitment success for SMBKC, as with many crab species, is driven by environmental conditions. In the Bering Sea recent environmental conditions appear to be unfavorable for recruitment success for this stock, which may be due to the longer larval duration of blue king crab (reference). 

The most biologically and environmental plausible projection would be projection 4, which suggests that it would be unlikely for the stock to rebuild to the current $B_{MSY}$ proxy under current recruitment conditions. However, adjusting the $B_{MSY}$ time frame (projection 5) would allow the stock to rebuild to a a more representative $B_{MSY}$ that is based on current recruitment conditions. 

Combinations of the projections, weighted based on their plausibility, are possible but more justification and thought is needed to determine why these combinations would be a better representation of the current biology and environment of the stock. Also, reasoning for the weighting of projections in a combination would need to be established. 


## Tables 


\begin{table}[ht]
\centering
\caption{$B_{MSY}$ proxy options for 2018 model 3, all Tier 4b.} 
\label{tab:B_msy proxy}
\begin{tabular}{lcccccccc}
  \hline
  Year & Basis for $B_\mathit{MSY}$ & $B_\mathit{MSY}$ proxy & MSST & Biomass($MMB_{mating}$) & B/$B_{MSY}$ & $F_{OFL}$ & M \\ 
  \hline
  2018/19 & 1978-2017 & 3.48 & 1.74 & 1.09 & 0.31 & 0.041 & 0.18 \\ 
  2018/19 & 1978-2017 & 2.03 & 1.015 & 1.08 & 0.53 & 0.087 & 0.18 \\ 
  \hline
\end{tabular}
\end{table}


\begin{table}[ht]
\centering
\caption{$T_{min}$ for each projection version d with no directed fishing (F=0).} 
\label{tab:t_min}
\begin{tabular}{lcccccccc}
  \hline
  Projection & recruitment & $B_\mathit{MSY}$ proxy & recruitment yrs & $T_{min}$ \\ 
  \hline
  1 & random recruitment & 1978-2017 & 1978-2017 & 7.5 years \\ 
  2 & ricker & 1979-2017 &  & 16.5 years \\
  3 & Beverton-Holt & 1979-2017 &  & 14.5 years \\
  4 & random recruitment & 1978-2017 & 1996-2017 & 100+ years \\
  5 & random recruitment & 1996-2017 & 1996-2017 & 10.5 years \\
  6 & random recruitment & 1978-2017 & 1999-2017 & 100+ years \\
  7 & random recruitment & 1978-2017 & 1989-2017 & 10 years \\
  \hline
\end{tabular}
\end{table}

\pagebreak 

## Figures