---
title: "Saint Matthew Island Blue King Crab update 2021"
author: "| Katie Palof$^1$, Jie Zheng$^1$ \n| $^1$Alaska Department of Fish and Game,
  katie.palof@alaska.gov and jie.zheng@alaska.gov\n"
date: "`r format(Sys.time(), '%B %Y')`"
output:
  pdf_document:
    toc: no
  bookdown::pdf_document2:
    fig_caption: yes
    includes: null
    toc: no
---
\pagenumbering{arabic}

```{r global_options, include=FALSE, echo = FALSE, message = FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(fig.width = 12, fig.height = 7, echo = FALSE, warning = FALSE, message = FALSE,  dpi=300)
#\pagenumbering{gobble}
```

# Summary {-}
The Saint Matthew Island blue king crab (SMBKC) assessment is now on a biennial cycle (approved by the CPT in Jan 2021, SSC in Feb 2021). 2021 is the "off" year in the cycle, so typically only an update to determine overfishing status in the 2020/21 season would be needed, however, multi-year OFLs and ABCs were NOT set in the September 2020 SAFE therefore those need to be set for the 2021/22 season.

The most recent assessment was conducted in September 2020 (Palof et al. 2020). In that assessment and this update, estimated total male catch is the sum of fishery-reported retained catch, estimated male discard mortality in the directed fishery, and estimated male bycatch mortality in the groundfish fisheries and other crab fisheries. Since the directed fishery is closed the total catch is the sum of the bycatch mortality in the groundfish fisheries and other crab fisheries. 

Based on the 2020 accepted model for SMBKC, the estimate for mature male biomass was below the minimum stock-size threshold (MSST) in 2020/21 and continues to be in an "overfished" condition, despite a directed fishery closure since the 2016/17 season. A rebuilding plan for SMBKC was put into place in 2020 and progress towards rebuilding will be documented in the 2022 SAFE. Rebuilding progress is updated on a biennial cycle and will coincide with the full assessment years. Total catch for 2020/21 is below the OFL, overfishing did not occur on this stock in 2020/21 (Tables \@ref(tab:status) and  \@ref(tab:ofl-basis)). 

Since no model runs are performed in an off cycle assessment year, the status of the stock is expected to be the same for the 2021/22 season, and therefore the OFL and ABC (using a 25% buffer as previously set in 2020) would be the same. Bycatch mortality from the 2020/21 season is insufficient to affect the status determination for this stock. 
 
 
 \begin{table}[ht]
 \centering
 \caption{Status and catch specifications (1000 t) for the base model.}
 \label{tab:status}
 \begin{tabular}{lccccccc}
  \hline
  & & Biomass & & Retained & Total & & \\
  Year & MSST & ($\mathit{MMB}_\text{mating}$) & TAC & catch & male catch & OFL & ABC \\
  \hline
  2016/17 & 1.97 & 2.23 & 0.00 & 0.00 & 0.001 & 0.14 & 0.11 \\
  2017/18 & 1.85 & 2.05 & 0.00 & 0.00 & 0.003 & 0.12 & 0.10 \\
  2018/19 & 1.74 & 1.15 & 0.00 & 0.00 & 0.001 & 0.04 & 0.03 \\
  2019/20 & 1.67 & 1.06 & 0.00 & 0.00 & 0.001 & 0.04 & 0.03 \\
  2020/21 &      & 1.12 & 0.00 & 0.00 & 0.001 & 0.05 & 0.04 \\
  2021/22 &      & 1.12 &  &  &  & 0.05 & 0.04 \\
  \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Status and catch specifications (million pounds) for the base model.}
\label{tab:status-pounds}
\begin{tabular}{lccccccc}
  \hline
  & & Biomass & & Retained & Total & & \\
  Year & MSST & ($\mathit{MMB}_\text{mating}$) & TAC & catch & male catch & OFL & ABC \\
  \hline
  2016/17 & 4.3 & 4.91 & 0.000 & 0.000 & 0.002  & 0.31 & 0.25 \\ 
  2017/18 & 4.1 & 2.85 & 0.000 & 0.000 & 0.007  & 0.27 & 0.22 \\ 
  2018/19 & 3.84 & 2.54 & 0.000 & 0.000 & 0.002 & 0.08 & 0.07 \\
  2019/20 & 3.68 & 2.34 & 0.000 & 0.000 & 0.002 & 0.096 & 0.08 \\
  2020/21 &      & 2.48 & 0.000 & 0.000 & 0.002 & 0.112 & 0.08  \\
  2021/22 &      & 2.48 &  &  &  & 0.112 & 0.08  \\
  \hline
\end{tabular}
\end{table}


**Basis for the OFL**: Estimated mature-male biomass (MMB) on 15 February is used as the measure of 
 biomass for this Tier 4 stock, with males measuring $\ge$ 105 mm CL considered mature. 
 The $B_\mathit{MSY}$ proxy is obtained by averaging estimated MMB over a specific reference period, and current CPT/SSC guidance recommends using the full assessment time frame (1978 - 2019) as the default reference period. 

\begin{table}[ht]
\centering
\caption{Basis for the OFL (1000 t) from the base model.}
\label{tab:ofl-basis}
\begin{tabular}{lcccccccc}
  \hline
  & & & Biomass & & & & & Natural \\ 
  Year & Tier & $B_\mathit{MSY}$ & ($\mathit{MMB}_\text{mating}$) & $B/B_\mathit{MSY}$ & $F_\mathit{OFL}$ & $\gamma$ & Basis for $B_\mathit{MSY}$ & mortality \\ 
  \hline
  2016/17 & 4b & 3.67 & 2.23 & 0.61 & 0.09 & 1 & 1978-2016 & 0.18 \\ 
  2017/18 & 4b & 3.86 & 2.05 & 0.53 & 0.08 & 1 & 1978-2017 & 0.18 \\
  2018/19 & 4b & 3.7  & 1.15 & 0.35 & 0.043 & 1 & 1978-2017 & 0.18 \\
  2019/20 & 4b & 3.48 & 1.06 & 0.31 & 0.042 & 1 & 1978-2018 & 0.18 \\ 
  2020/21 & 4b & 3.34 & 1.12 & 0.34 & 0.047 & 1 & 1978-2019 & 0.18 \\
  2021/22 & 4b & 3.34 & 1.12 & 0.34 & 0.047 & 1 & 1978-2019 & 0.18 \\
  \hline
\end{tabular}
\end{table}

\pagebreak