---
title: "Saint Matthew Island Blue King Crab update 2023"
author: "| Katie Palof$^1$ $^1$Alaska Department of Fish and Game,
  katie.palof@alaska.gov \n"
date: "`r format(Sys.time(), '%B %Y')`"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    includes: null
    toc: no
  pdf_document:
    toc: no
---
\pagenumbering{arabic}

```{r global_options, include=FALSE, echo = FALSE, message = FALSE, warning=FALSE}
library(knitr)
opts_chunk$set(fig.width = 12, fig.height = 7, echo = FALSE, warning = FALSE, message = FALSE,  dpi=300)
#\pagenumbering{gobble}
```

# Summary {-}
The Saint Matthew Island blue king crab (SMBKC) assessment is now on a biennial cycle occurring in even years (approved by the CPT in Jan 2021, SSC in Feb 2021). 2023 is the "off" year in the cycle, so only an update to determine overfishing status in the 2022/23 season is needed.

The most recent assessment was conducted in September 2022 (Palof et al. 2022). In that assessment and this update, estimated total male catch is the sum of fishery-reported retained catch, estimated male discard mortality in the directed fishery, and estimated male bycatch mortality in the groundfish fisheries and other crab fisheries. Since the directed fishery is closed the total catch is the sum of the bycatch mortality in the groundfish fisheries and other crab fisheries. No bycatch occurred in the crab fishery so total total catch is bycatch mortality from groundfish fisheries.

Total catch mortality is less than the ABC therefore overfishing is not occuring in the 2022/23 season.

 \begin{table}[ht]
 \centering
 \caption{Status and catch specifications (1000 t) for the base model.}
 \label{tab:status}
 \begin{tabular}{lccccccc}
  \hline
  & & Biomass & & Retained & Total & & \\
  Year & MSST & ($\mathit{MMB}_\text{mating}$) & TAC & catch & male catch & OFL & ABC \\
  \hline
  2018/19 & 1.74 & 1.15 & 0.00 & 0.00 & 0.001 & 0.04 & 0.03 \\
  2019/20 & 1.67 & 1.06 & 0.00 & 0.00 & 0.001 & 0.04 & 0.03 \\
  2020/21 & 1.65 & 1.14 & 0.00 & 0.00 & 0.001 & 0.05 & 0.04 \\
  2021/22 & 1.63 & 1.18 & 0.00 & 0.00 & 0.001 & 0.05 & 0.04 \\
  2022/23 &      & 1.31 & 0.00 & 0.00 & 0.002 & 0.066 & 0.0497 \\
  2023/24 &      & 1.31 &  &  &  & 0.066 & 0.0497 \\
  \hline
\end{tabular}
\end{table}

\begin{table}[ht]
\centering
\caption{Status and catch specifications (million pounds) for the base model.}
\label{tab:status-pounds}
\begin{tabular}{lccccccc}
  \hline
  & & Biomass & & Retained & Total & & \\
  Year & MSST & ($\mathit{MMB}_\text{mating}$) & TAC & catch & male catch & OFL & ABC \\
  \hline
  2018/19 & 3.84 & 2.54 & 0.000 & 0.000 & 0.002 & 0.08 & 0.07 \\
  2019/20 & 3.68 & 2.34 & 0.000 & 0.000 & 0.002 & 0.096 & 0.08 \\
  2020/21 & 3.64 & 2.52 & 0.000 & 0.000 & 0.002 & 0.112 & 0.08  \\
  2021/22 & 3.59 & 2.59 & 0.000 & 0.000 & 0.002 & 0.112 & 0.08  \\
  2022/23 &      & 2.9 & 0.000 & 0.000 & 0.004 & 0.146 & 0.11  \\
  2023/24 &      & 2.9 &  &  &  & 0.146 & 0.11  \\
  \hline
\end{tabular}
\end{table}


